package arch.configs.mk

import arch.configs.{ ISA, Parameters, TopModuleName }
import java.nio.charset.StandardCharsets
import java.nio.file.{ Files, Path, Paths }

object MakeCodegen {
  type Options = MakeCodegenOptions
  val Options = MakeCodegenOptions

  type OutputPaths = MakeOutputPaths
  val OutputPaths = MakeOutputPaths

  def emit(p: Parameters, config: String): Unit =
    emit(p, OutputPaths(config = Paths.get(config)), Options())

  def emit(p: Parameters, config: String, options: Options): Unit =
    emit(p, OutputPaths(config = Paths.get(config)), options)

  def emit(p: Parameters, paths: OutputPaths, options: Options = Options()): Unit = {
    val configPath = resolveOutputPath(paths.config)
    write(configPath, render(p, options))
    println(s"[MakeCodegen] generated Make config -> $configPath")
  }

  def render(p: Parameters, options: Options = Options()): String = {
    val isa = p(ISA)
    val w   = new MakeWriter

    w.line("# This file is generated by arch.configs.mk.MakeCodegen.")
    w.line("# It only contains hardware target parameters exported from Scala.")
    w.line("# Build options must be generated by Kconfig.")
    w.line()

    assign(w, "TARGET_FAMILY", isa.family)
    assign(w, "TARGET_ARCH", isa.name)
    assign(w, "TOP_MODULE", p(TopModuleName))
    w.line()

    if (options.emitMakeAliases) {
      w.line("# Existing sims/Makefile compatibility aliases.")
      rawAssign(w, "FAMILY", "$(TARGET_FAMILY)")
      rawAssign(w, "ARCH", "$(TARGET_ARCH)")
      w.line()
    }

    w.result
  }

  private def assign(w: MakeWriter, name: String, value: String): Unit =
    w.line(s"$name := ${makeEscape(value)}")

  private def rawAssign(w: MakeWriter, name: String, value: String): Unit =
    w.line(s"$name := $value")

  private def makeEscape(value: String): String =
    value.replace("#", "\\#")

  private def resolveOutputPath(path: Path): Path =
    path.normalize()

  private def write(path: Path, text: String): Unit = {
    val parent = path.getParent
    if (parent != null) {
      Files.createDirectories(parent)
    }

    Files.write(path, text.getBytes(StandardCharsets.UTF_8))
  }

  final private class MakeWriter {
    private val builder = new StringBuilder

    def line(text: String = ""): Unit = {
      builder.append(text)
      builder.append('\n')
    }

    def result: String = builder.result()
  }
}
