package arch.configs.cmake

import arch.configs.{ ISA, Parameters, TopModuleName }
import java.nio.charset.StandardCharsets
import java.nio.file.{ Files, Path, Paths }

object CMakeCodegen {
  type Options = CMakeCodegenOptions
  val Options = CMakeCodegenOptions

  type OutputPaths = CMakeOutputPaths
  val OutputPaths = CMakeOutputPaths

  def emit(p: Parameters, config: String): Unit =
    emit(p, OutputPaths(config = Paths.get(config)), Options())

  def emit(p: Parameters, config: String, options: Options): Unit =
    emit(p, OutputPaths(config = Paths.get(config)), options)

  def emit(p: Parameters, paths: OutputPaths, options: Options = Options()): Unit = {
    val configPath = resolveOutputPath(paths.config)
    write(configPath, render(p, options))
    println(s"[CMakeCodegen] generated CMake config -> $configPath")
  }

  def render(p: Parameters, options: Options = Options()): String = {
    val isa = p(ISA)
    val w = new CMakeWriter

    w.line("# This file is generated by arch.configs.cmake.CMakeCodegen.")
    w.line("# It only contains hardware target parameters exported from Scala.")
    w.line("# Build options must be generated by Kconfig.")
    w.line()

    set(w, "TARGET_FAMILY", isa.family)
    set(w, "TARGET_ARCH", isa.name)
    set(w, "TOP_MODULE", p(TopModuleName))
    w.line()

    w.result
  }

  private def set(w: CMakeWriter, name: String, value: String): Unit =
    w.line(s"""set($name "${cmakeEscape(value)}")""")

  private def cmakeEscape(value: String): String =
    value.replace("\\", "\\\\").replace("\"", "\\\"")

  private def resolveOutputPath(path: Path): Path =
    path.normalize()

  private def write(path: Path, text: String): Unit = {
    val parent = path.getParent
    if (parent != null) {
      Files.createDirectories(parent)
    }

    Files.write(path, text.getBytes(StandardCharsets.UTF_8))
  }

  private final class CMakeWriter {
    private val builder = new StringBuilder

    def line(text: String = ""): Unit = {
      builder.append(text)
      builder.append('\n')
    }

    def result: String = builder.result()
  }
}
